networks:
  byte_driver_network:

services:

  mysql_userDB:
    image:  mysql
    ports:
      - 8000:3306
    restart: always
    build:
      context: ./backend/userService
      dockerfile: mysql_userDB.dockerfile
    volumes:
      - mysql_userDB_data:/var/lib/mysql
    networks:
      - byte_driver_network
    
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - byte_driver_network
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  user_service:
    depends_on:
      - mysql_userDB
    networks:
      - byte_driver_network
    build: ./backend/userService
    ports:
      - "8080:8080"


volumes:
  kafka_data:
    driver: local
  mysql_userDB_data: {}