CREATE DATABASE UserDB;

USE UserDB;

CREATE TABLE Users(
    UserID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Password VARCHAR(200) NOT NULL,
    PhoneNumber BIGINT NOT NULL UNIQUE, 
    Email VARCHAR(100) NOT NULL UNIQUE,
    Type VARCHAR(10) NOT NULL,
    PRIMARY KEY (UserID)
) AUTO_INCREMENT=1000;